# Generated by Django 5.0.2 on 2024-03-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_secu', '0002_remove_order_user_uploadedfile_uploadhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='hash_value',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='hash_value',
            field=models.CharField(default='', max_length=64),
        ),
    ]
