# Generated by Django 5.0.2 on 2024-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_secu', '0005_alter_uploadedfile_hash_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='hash_value',
            field=models.CharField(default='default_hash_value', max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='hash_value',
            field=models.CharField(default='default_hash_value', max_length=64),
        ),
    ]
