# Generated by Django 5.0.2 on 2024-03-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_secu', '0006_uploadhistory_hash_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='hash_value',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='hash_value',
            field=models.CharField(max_length=64),
        ),
    ]
