# Generated by Django 5.0.2 on 2024-03-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_secu', '0015_remove_uploadedfile_hash_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='hash_value',
        ),
    ]
