# Generated by Django 5.0.2 on 2024-03-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_secu', '0018_uploadedfile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='uploadhistory',
            old_name='user',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='username',
        ),
    ]
