# Generated by Django 5.0.2 on 2024-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_secu', '0019_rename_user_uploadedfile_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='hash_value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
